project:
  type: website
  output-dir: docs

website:
  title: "How Stress, BMI, and Lifestyle Shape Sleep Health"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "My website"
        href: https://reimn11.github.io
        target: _blank
format:
  html:
    theme: 
      light: mintty
      dark: superhero
    css: styles.css
    toc: true

editor: visual


