project:
  type: website
  output-dir: docs
  

website:
  title: "Dashboards"
  navbar:
    left:
      - href: index.qmd
        text: Starwars
      - penguins.qmd
      - icon: github
        href: https://github.com/reimn11
        target: blank
      - icon: house
        href: https://reimn11.github.io
        target: blank
      

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: true

editor: visual

